services:
  - type: web
    name: q3-workbench
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3721
      - key: WEBHOOK_DAILY_REVIEW
        value: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=4eb139cc-e9ef-462d-8ef0-8559e4b94ba1
